services:
  webapp:
    build: .
    container_name: video_stream
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
    expose:
      - "8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://root:root@postgres:5432/mydatabase
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - webapp
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
